### ISSUE TITLE
installing and configuring

### ISSUE THREAD

**Issue by splaisan** [MaestSi/MetONTIIME#1]
I downloaded the fasta from NCBI from project 33175 under **33175_sequences.fasta** but I cannot make it a DB with your tutorial:
Do I need to download the same project data in a different format?

You write 'Send to' 'File' but do not comment on the other export options!

Where do I get the second file **PRJNA33175_taxonomy.qza**? I searched this in Qiime too but do not find any help.

Can you please clarify.

Thanks

```
./Import_database.sh 33175_sequences.fasta
WARNING: A conda environment already exists at '/opt/biotools/miniconda3/envs/entrez_qiime_env'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/biotools/miniconda3/envs/entrez_qiime_env

  added / updated specs:
    - python=2.7


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.9.11-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.9.11-py27_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1c-h516909a_0
  pip                conda-forge/linux-64::pip-19.2.3-py27_0
  python             conda-forge/linux-64::python-2.7.15-h5a48372_1009
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-41.2.0-py27_0
  sqlite             conda-forge/linux-64::sqlite-3.29.0-hcee41ef_1
  tk                 conda-forge/linux-64::tk-8.6.9-hed695b0_1003
  wheel              conda-forge/linux-64::wheel-0.33.6-py27_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate entrez_qiime_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/d7/b1/3367ea1f372957f97a6752ec725b87886e12af1415216feec9067e31df70/numpy-1.16.5-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.16.5
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting cogent
Installing collected packages: cogent
Successfully installed cogent-1.9
--2019-09-16 11:07:04--  ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz
           => ‘nucl_gb.accession2taxid.gz’
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.7, 2607:f220:41e:250::12
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.7|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy/accession2taxid ... done.
==> SIZE nucl_gb.accession2taxid.gz ... 1879248969
==> PASV ... done.    ==> RETR nucl_gb.accession2taxid.gz ... done.
Length: 1879248969 (1.8G) (unauthoritative)

nucl_gb.accession2taxid.gz                        100%[=============================================================================================================>]   1.75G  33.1MB/s    in 55s     

2019-09-16 11:08:00 (32.9 MB/s) - ‘nucl_gb.accession2taxid.gz’ saved [1879248969]

gzip: nucl_gb.accession2taxid already exists; do you wish to overwrite (y or n)? y
--2019-09-16 11:09:08--  ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
           => ‘taxdump.tar.gz.1’
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.7, 2607:f220:41e:250::7
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.7|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy ... done.
==> SIZE taxdump.tar.gz ... 49120339
==> PASV ... done.    ==> RETR taxdump.tar.gz ... done.
Length: 49120339 (47M) (unauthoritative)

taxdump.tar.gz.1                                  100%[=============================================================================================================>]  46.84M  23.4MB/s    in 2.0s    

2019-09-16 11:09:11 (23.4 MB/s) - ‘taxdump.tar.gz.1’ saved [49120339]

citations.dmp
delnodes.dmp
division.dmp
gencode.dmp
merged.dmp
names.dmp
nodes.dmp
gc.prt
readme.txt
Traceback (most recent call last):
  File "./entrez_qiime/entrez_qiime.py", line 24, in <module>
    from cogent.parse.ncbi_taxonomy import NcbiTaxonomyFromFiles
ImportError: No module named cogent.parse.ncbi_taxonomy
Imported 33175_sequences.fasta as DNAFASTAFormat to /opt/biotools/MetONTIIME/33175_sequences_sequence.qza
Usage: qiime tools import [OPTIONS]

  Import data to create a new QIIME 2 Artifact. See https://docs.qiime2.org/
  for usage examples and details on the file types and associated semantic
  types that can be imported.

Options:
  --type TEXT             The semantic type of the artifact that will be
                          created upon importing. Use --show-importable-types
                          to see what importable semantic types are available
                          in the current deployment.                [required]
  --input-path PATH       Path to file or directory that should be imported.
                                                                    [required]
  --output-path ARTIFACT  Path where output artifact should be written.
                                                                    [required]
  --input-format TEXT     The format of the data to be imported. If not
                          provided, data must be in the format expected by the
                          semantic type provided via --type.
  --show-importable-types Show the semantic types that can be supplied to
                          --type to import data into an artifact.
  --show-importable-formats
                          Show formats that can be supplied to --input-format
                          to import data into an artifact.
  --help                  Show this message and exit.

                    There was a problem with the command:                     
 (1/1) Invalid value for "--input-path": Path
  "/opt/biotools/MetONTIIME/33175_sequences_accession_taxonomy.txt" does not
  exist.
```

**Comment by MaestSi** [comment]
Hi,
I have updated the README to specify that when downloading the file you should also set the Format to FASTA and then click Create File. Did you already download the file in fasta format, or in the default summary format? The taxonomy file PRJNA33175_taxonomy.qza should be generated by the Import_database.sh script too. I reran the full pipeline again on the same fasta file recloning and redownloading files too and did not encounter any error. From your error:
```
File "./entrez_qiime/entrez_qiime.py", line 24, in <module>
    from cogent.parse.ncbi_taxonomy import NcbiTaxonomyFromFiles
ImportError: No module named cogent.parse.ncbi_taxonomy
```
it seems that the python module  cogent.parse.ncbi_taxonomy is not being installed in entrez_qiime_env environment as it was supposed to be, although the log says it was (Successfully installed cogent-1.9).
To confirm this is the issue, you could try running:
```
source activate entrez_qiime_env
python
import cogent.parse.ncbi_taxonomy
```
with the last command typed inside the python command line.
Does it complain about the  cogent.parse.ncbi_taxonomy missing package?

**Comment by splaisan** [comment]
Hi Simone, there is definitely an issue with the install. I redid it several times including running the package installs manually but never succeeded, probably because of newer python versions on my machine.
Thanks for helping

```
(entrez_qiime_env) u0002316@gbw-s-pacbio01:/opt/biotools/MetONTIIME$ python
Python 2.7.12 (default, Aug 22 2019, 16:36:40) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cogent.parse.ncbi_taxonomy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cogent.parse.ncbi_taxonomy
>>> 
```

**Comment by splaisan** [comment]
could it come from the bloody conda-forge being in my .condarc?

**Comment by MaestSi** [comment]
Hi Stephan,
the list of installed packages looks very similar to mine, and moreover cogent looks like installed too.
(entrez_qiime_env) simone@r910-ddlab:~/MinION/MinION_scripts/MetONTIIME/import_test$ conda list
```
# packages in environment at /home/simone/miniconda3/envs/entrez_qiime_env:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py27_0    conda-forge
cogent                    1.9                      pypi_0    pypi
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.5                   pypi_0    pypi
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.2.3                   py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                41.2.0                   py27_0    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
The only major difference that I spot is the gcc version when starting python, that is v7.3.0 for me and v5.4.0 for you:
```
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:39:44)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
I think -but I am not expert at all about this- this should not be related with the gcc version that you installed on your machine, but with the gcc version was used to compile python from anaconda. So, my suggestion would be to try downloading a newer miniconda3, repeat the cloning of the repository and the installation, and see what happens.
I don't think one conda channel should be responsible for this.
Let me know if you try it out!

**Comment by MaestSi** [comment]
Another possibility would be to try installing cogent with conda:
```
source activate entrez_qiime_env
conda install -c bioconda cogent
```
And then repeat the
```
python
import cogent.parse.ncbi_taxonomy
```
check to see if it worked.

**Comment by splaisan** [comment]
so messy!
I installed gcc within the env
I tried deinstall cogent and reinstall it
keeps failing, whatever I do

```
conda install -c bioconda cogent
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                        

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package zlib conflicts for:
python=2.7 -> zlib[version='>=1.2.11,<1.3.0a0']
cogent -> zlib[version='1.2.11.*|>=1.2.11,<1.3.0a0']
Package ncurses conflicts for:
python=2.7 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0']
Package ca-certificates conflicts for:
python=2.7 -> ca-certificates
Package libffi conflicts for:
python=2.7 -> libffi[version='3.2.*|>=3.2.1,<4.0a0']
Package mpi4py conflicts for:
cogent -> mpi4py[version='>=1.0']
Package pip conflicts for:
python=2.7 -> pip
Package sqlalchemy conflicts for:
cogent -> sqlalchemy[version='>=0.5']
Package numpy conflicts for:
cogent -> numpy[version='>=1.3']
Package mysql-python conflicts for:
cogent -> mysql-python[version='>=1.2.2']
Package sqlite conflicts for:
python=2.7 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0']
Package libgcc-ng conflicts for:
python=2.7 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package readline conflicts for:
python=2.7 -> readline[version='7.*|>=7.0,<8.0a0']
Package matplotlib conflicts for:
cogent -> matplotlib[version='>=1.1.0']
Package tk conflicts for:
python=2.7 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0']
Package libstdcxx-ng conflicts for:
python=2.7 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|1.0.*,>=1.0.2l,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a']
```

BUT `pip install cogent ` does it apparently! and I now can import in python.
finger crossed, I retry the Import script

**Comment by MaestSi** [comment]
I have updated the **Import_database.sh** script so that it does not re-downloads taxonomy files from NCBI, in case you already have them in the current directory.

**Comment by splaisan** [comment]
I tried update the script with git but get the following. How can I pull?

```
(MetONTIIME_env) u0002316@gbw-s-pacbio01:/opt/biotools/MetONTIIME$ git pull
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/MaestSi/MetONTIIME
   9e4bfb8..9c1730a  master     -> origin/master
Updating 9e4bfb8..9c1730a
error: Your local changes to the following files would be overwritten by merge:
	Import_database.sh
	README.md
Please, commit your changes or stash them before you can merge.
Aborting
```

**Comment by MaestSi** [comment]
I would simply git clone the repository again to some other path, and then copy the Import_database.sh file into the MetONTIIME directory. Maybe changes were not considered committed, since I had not logout yet?

**Comment by splaisan** [comment]
Thanks Simone for the effort but the cogent is again failing again with same error.
I think I will quit here, too dangerous to change the GCC of my ubuntu server which is now at the official 5.8 version and all combinations of packages I tried to solve the entrez_qiime_env fail.

When you would have a fully working entrez_qiime_env setup for ubuntu 16 I would be happy to try again.

**Comment by MaestSi** [comment]
I would try installing gcc in the conda environment as you did before, and then it should be enough to copy paste the lines I pasted a few posts ago...I think the only problem is being able to import the cogent package in python. I did not develop entrez_qiime myself, so it is not something I could fix.

**Comment by splaisan** [comment]
YES!

it finally worked after installing gcc within the entrez_qiime_env (conda install -c anaconda gcc)
I could then load the library inpython 
But I failed to run the command './entrez_qiime/entrez_qiime.py -i $DB_FASTA -n ./taxonomy/taxdump -a ./taxonomy/nucl_gb.accession2taxid'
Until I added the full python path in front of it (weird as python version gives the same version for both)

```
python --version
Python 2.7.16 :: Anaconda, Inc.

/opt/biotools/miniconda3/envs/entrez_qiime_env/bin/python --version
Python 2.7.16 :: Anaconda, Inc.
```
 
An some say that Python is much better than Perl (bugie!)
Anyway, I got the necessary file PRJNA33175_Bacterial_sequences_accession_taxonomy.txt and could proceed with the two qiime commands from your script

Thanks for your patience, you may close this ticket at any time, I will now explore the remaining of the tutorial.

Buonasera :-)

**Comment by MaestSi** [comment]
Very glad it worked! But just to understand how to better fix it for potential future users who may encounter a similar issue, were you running:
`python ./entrez_qiime/entrez_qiime.py -i $DB_FASTA -n ./taxonomy/taxdump -a ./taxonomy/nucl_gb.accession2taxid`
or just
`./entrez_qiime/entrez_qiime.py -i $DB_FASTA -n ./taxonomy/taxdump -a ./taxonomy/nucl_gb.accession2taxid`
Because if you did not specify that it was a python script, probably the system version was being called due to `#!/usr/bin/python` in the header of the python script.
Thanks

**Comment by splaisan** [comment]
I think you have a point, I did not include python and used the command as in your script so probably the python used was one that does not have access to cogent while when I specified the conda python it worked.
