### ISSUE TITLE
error in Vsearch

### ISSUE THREAD

**Issue by ma-diroma** [MaestSi/MetONTIIME#45]
Hi,

I am trying to use your pipeline. I have to say that I am using anaconda3 rather than miniconda3. I am testing the tool with your fast5 file. When I selected Vsearch as classifier, I got this error in my log file

```
vsearch v2.7.0_linux_x86_64, 251.8GB RAM, 24 cores
https://github.com/torognes/vsearch

Reading file /tmp/q2-QIIME1DemuxDirFmt-s6i2wtwh/seqs.fna 100%
725073 nt in 537 seqs, min 1252, max 1474, avg 1350
Dereplicating 100%
Sorting 100%
537 unique sequences, avg cluster 1.0, median 1, max 1
Writing output file 100%
Writing uc file, first part 100%
Writing uc file, second part 100%
Running external command line application. This may print messages to stdout and/or stderr.
The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.

Command: vsearch --derep_fulllength /tmp/q2-QIIME1DemuxDirFmt-s6i2wtwh/seqs.fna --output /tmp/q2-DNAFASTAFormat-b3flzjl1 --relabel_sha1 --relabel_keep --uc /tmp/tmp9ijq3nhx --qmask none --xsize --minseqlength 1 --fasta_width 0

Traceback (most recent call last):
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/q2cli/commands.py", line 339, in __call__
    results = action(**arguments)
  File "<decorator-gen-398>", line 2, in dereplicate_sequences
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/sdk/action.py", line 418, in _callable_executor_
    artifact = qiime2.sdk.Artifact._from_view(
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/sdk/result.py", line 312, in _from_view
    artifact._archiver = archive.Archiver.from_data(
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/core/archive/archiver.py", line 316, in from_data
    Format.write(rec, type, format, data_initializer, provenance_capture)
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/core/archive/format/v5.py", line 20, in write
    super().write(archive_record, type, format, data_initializer,
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/core/archive/format/v1.py", line 25, in write
    provenance_capture.finalize(
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/core/archive/provenance.py", line 320, in finalize
    self.write_citations_bib()
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/core/archive/provenance.py", line 311, in write_citations_bib
    self.citations.save(str(self.path / self.CITATION_FILE))
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/qiime2/core/cite.py", line 71, in save
    bp.dump(db, f, writer=writer)
  File "/home/mdiroma/anaconda3/envs/MetONTIIME_env/lib/python3.8/site-packages/bibtexparser/__init__.py", line 111, in dump
    bibtex_file.write(writer.write(bib_database))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0161' in position 3969: ordinal not in range(256)

```

So I tried to use blast rather than vsearch but I got the same error referring to vsearch.
Could you please help me?

Thanks,
Best wishes,
Maria Angela

**Comment by MaestSi** [comment]
Ciao! Could you please report the command you used? Thanks in advance.
SM

**Comment by ma-diroma** [comment]
Ciao Simone,

Thank you! It works!

Best,
ciao
Maria Angela
